server:
  port: 8765

#actuator ???? ??
#????: /actuator
#management:
#  endpoints:
#    web:
#      base-path: /hello

#http://localhost:8765/h2-console
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true

#socket
socket:
  localPort: 5555
  remotePort: 6666
  remoteIp: 127.0.0.1